### ISSUE TITLE
AAD, I want a custom menu for the scrollable widget

### ISSUE THREAD

**Issue by andypham29** [karlogonzales/ministocks-390#49]
## Description
As explained in the issue #44 , implementing a custom menu may be more feasible than reusing the current menu provided by the developer.

## Update
This issue has now more details regarding how to implement the custom menu. 

*Remove* and *Change Order* can be implemented in the sprint 6. Functionality of the settings in the *General* category can also be moved to next sprint if there is not enough time.

## Tasks
The custom menu will be broken down as follow:

**Stock Setup UI**
- [x] add #46 
- [x] *remove*
- [ ] *change order*
- [ ] update data #58 

**Stock Setup Funcitionality**
- [x] add #46 
- [x] *remove*
- [ ] *change order*
- [ ] update data #58 

**Genera Ul**
- [x] appearance #66
- [x] help #66
- [x] about #66

**General Functionality**
- [x] appearance #66
- [x] help #66
- [x] about #66

**Note:** Each feature is expected to also include a UI component. Write tests for your part.

## Discussion
For the *Add* functionality of the menu, check out how they are implemented in the current menu to help you implement them. 

Look into how to change to a different layout from current layout. Also check on how to change the layout dependent on what setting has been selected (similar to php). 

Click on each item of the menu for more detail.

**Comment by hasan-ahmed** [comment]
# ACCEPTANCE TESTS


ID | Test Description | Acceptance Requirement | Critical | Test Result | Comment
-- | -- | -- | -- | -- | --
1 | Verify that the new menu can be opened from the widget by clicking the custom button. | The system shall open a new view when the Custom button is clicked. | Yes | ACCEPTED:The System properly opens a new view. | There are currently two  functional menu buttons.Known bugs due to the functionalities of the menu not being connected to the widget yet.issue #43
2 | Verify that the stock setup functionality behaves properly in the new Custom Menu. | The system shall add a stock, remove a stock and update stock prices from the new custom menu controls | Yes | ACCEPTED:The system can properly add, remove and update stocks. |  
3 | Verify that the the UI preferences can be modified from the new custom menu. | The system shall change the change the background, change the text color and change the text font from the new custom menu controls. | Yes | ACCEPTED:The widget can properly modify the UI using the new custom menu |

**Comment by andypham29** [comment]
Change order and update from menu will not be implemented due to lack of time.
